// Objective-C API for talking to github.com/traconiq/tachoparser/pkg/mobile Go package.
//   gobind -lang=objc github.com/traconiq/tachoparser/pkg/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileOptions;
@class MobileParseResult;
@class MobileParser;

/**
 * Options configure certificate lookup for the Parser constructor.
 */
@interface MobileOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull pkS1Dir;
@property (nonatomic) NSString* _Nonnull pkS2Dir;
@end

/**
 * ParseResult contains the JSON payload produced by the parser along with its verification status.
 */
@interface MobileParseResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull payloadJSON;
@property (nonatomic) BOOL verified;
@end

/**
 * Parser exposes mobile-friendly helpers around the core parser.Service.
 */
@interface MobileParser : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped constructor Parser.NewParser with unsupported parameter or return types

/**
 * ParseCard parses tachograph driver card dumps and returns the result payload and verification status.
 */
- (MobileParseResult* _Nullable)parseCard:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
/**
 * ParseVehicleUnit parses vehicle unit dumps and returns the result payload and verification status.
 */
- (MobileParseResult* _Nullable)parseVehicleUnit:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
/**
 * ParseWithTimeout allows selecting the parser mode dynamically and applies a timeout (in milliseconds).
 */
- (MobileParseResult* _Nullable)parseWithTimeout:(NSData* _Nullable)data mode:(NSString* _Nullable)mode timeoutMillis:(long)timeoutMillis error:(NSError* _Nullable* _Nullable)error;
@end

// skipped function NewParser with unsupported parameter or return types


#endif
